/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sires;

import java.awt.Color;
import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/* AUTHOR ADSI-108
 *Version del software 1.0
*Fecha 06/10/2016
*/
public class EntradaSalida extends javax.swing.JInternalFrame {

    /*
      Creates new form EntradaSalida
     */
    public EntradaSalida() {
        initComponents();
        vNo.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        objeto = new javax.swing.JFrame();
        equipo = new javax.swing.JRadioButton();
        elemento = new javax.swing.JRadioButton();
        accesorio = new javax.swing.JRadioButton();
        opcion = new javax.swing.JComboBox<>();
        aceptarObj = new javax.swing.JButton();
        cancelarObj = new javax.swing.JButton();
        objetoTipo = new javax.swing.ButtonGroup();
        checkVehiculo = new javax.swing.ButtonGroup();
        persona = new javax.swing.JPanel();
        datos = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        apellidos = new javax.swing.JLabel();
        rol = new javax.swing.JLabel();
        ejemplo = new javax.swing.JTextField();
        ejemploB = new javax.swing.JButton();
        foto = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        vehiculo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vNo = new javax.swing.JRadioButton();
        vSi = new javax.swing.JRadioButton();
        tipoV = new javax.swing.JLabel();
        placa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        objetoScroll = new javax.swing.JScrollPane();
        objetos = new javax.swing.JPanel();
        agregar = new javax.swing.JButton();

        objetoTipo.add(equipo);
        equipo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        equipo.setText("Equipo");

        objetoTipo.add(elemento);
        elemento.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        elemento.setText("Elemento");

        objetoTipo.add(accesorio);
        accesorio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        accesorio.setText("Accesorio");

        opcion.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lenovo", "Alien Ware", "Asus" }));

        aceptarObj.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        aceptarObj.setText("Aceptar");
        aceptarObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarObjActionPerformed(evt);
            }
        });

        cancelarObj.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cancelarObj.setText("Cancelar");
        cancelarObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarObjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout objetoLayout = new javax.swing.GroupLayout(objeto.getContentPane());
        objeto.getContentPane().setLayout(objetoLayout);
        objetoLayout.setHorizontalGroup(
            objetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(objetoLayout.createSequentialGroup()
                .addGroup(objetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, objetoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(opcion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(objetoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(equipo)
                        .addGap(18, 18, 18)
                        .addComponent(elemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accesorio)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, objetoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(aceptarObj)
                .addGap(18, 18, 18)
                .addComponent(cancelarObj)
                .addGap(77, 77, 77))
        );
        objetoLayout.setVerticalGroup(
            objetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(objetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(objetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equipo)
                    .addComponent(elemento)
                    .addComponent(accesorio))
                .addGap(18, 18, 18)
                .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(objetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarObj)
                    .addComponent(cancelarObj))
                .addContainerGap())
        );

        nombre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        nombre.setText("Nombre");

        id.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        id.setText("Identificación");

        apellidos.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        apellidos.setText("Apellidos");

        rol.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        rol.setText("Rol");

        ejemploB.setText("ok");
        ejemploB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemploBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosLayout = new javax.swing.GroupLayout(datos);
        datos.setLayout(datosLayout);
        datosLayout.setHorizontalGroup(
            datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosLayout.createSequentialGroup()
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre)
                    .addComponent(apellidos)
                    .addComponent(id)
                    .addComponent(rol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ejemploB)
                    .addComponent(ejemplo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        datosLayout.setVerticalGroup(
            datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosLayout.createSequentialGroup()
                .addComponent(nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rol)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(datosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ejemplo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(ejemploB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        foto.setBackground(new java.awt.Color(177, 245, 254));

        jLabel5.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N
        jLabel5.setText("Foto");

        javax.swing.GroupLayout fotoLayout = new javax.swing.GroupLayout(foto);
        foto.setLayout(fotoLayout);
        fotoLayout.setHorizontalGroup(
            fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fotoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        fotoLayout.setVerticalGroup(
            fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fotoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout personaLayout = new javax.swing.GroupLayout(persona);
        persona.setLayout(personaLayout);
        personaLayout.setHorizontalGroup(
            personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        personaLayout.setVerticalGroup(
            personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Vehiculo");

        checkVehiculo.add(vNo);
        vNo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        vNo.setText("No");
        vNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vNoItemStateChanged(evt);
            }
        });

        checkVehiculo.add(vSi);
        vSi.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        vSi.setText("Si");
        vSi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vSiItemStateChanged(evt);
            }
        });

        tipoV.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tipoV.setText("Tipo");

        placa.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        placa.setText("Placa");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Operador");

        javax.swing.GroupLayout vehiculoLayout = new javax.swing.GroupLayout(vehiculo);
        vehiculo.setLayout(vehiculoLayout);
        vehiculoLayout.setHorizontalGroup(
            vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vehiculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(placa)
                    .addComponent(tipoV)
                    .addGroup(vehiculoLayout.createSequentialGroup()
                        .addComponent(vSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vNo)))
                .addGap(38, 38, 38))
            .addGroup(vehiculoLayout.createSequentialGroup()
                .addGroup(vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehiculoLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1))
                    .addGroup(vehiculoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vehiculoLayout.setVerticalGroup(
            vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vNo)
                    .addComponent(vSi))
                .addGap(18, 18, 18)
                .addComponent(tipoV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(placa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        agregar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        agregar.setText("+");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout objetosLayout = new javax.swing.GroupLayout(objetos);
        objetos.setLayout(objetosLayout);
        objetosLayout.setHorizontalGroup(
            objetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, objetosLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        objetosLayout.setVerticalGroup(
            objetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(objetosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        objetoScroll.setViewportView(objetos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(vehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(objetoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(objetoScroll)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
        Agrega un frame encargado de filtrar consultar y seleccionar un objeto
        perteneciente a la persona que realiza el ingreso.  
    */
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        objeto.setSize(300,155);
        objeto.setVisible(true);
        
    }//GEN-LAST:event_agregarActionPerformed
    /*
        Se encarga de cerrar la ventana donde se muestran los objetos disponibles
        por si se desea cancelar la accion.        
    */
    private void cancelarObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarObjActionPerformed
        objeto.dispose();
    }//GEN-LAST:event_cancelarObjActionPerformed
    
    private void aceptarObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarObjActionPerformed
        JLabel obj =new JLabel("holaaaaa");
        objetos.add(obj);
        obj.setVisible(true);
        objetos.repaint();
        objetos.updateUI();
        
        System.out.println(nombre);
        System.out.println(obj.isVisible());
        System.out.println(obj);
        
        
        
    }//GEN-LAST:event_aceptarObjActionPerformed

    private void vNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vNoItemStateChanged
        if(vNo.isSelected()){
            tipoV.setVisible(false);
            placa.setVisible(false);
        }
            
    }//GEN-LAST:event_vNoItemStateChanged

    private void vSiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vSiItemStateChanged
         if(vSi.isSelected()){
            tipoV.setVisible(true);
            placa.setVisible(true);
        }
    }//GEN-LAST:event_vSiItemStateChanged

    private void ejemploBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemploBActionPerformed
       String sql="SELECT codigo, identificacion, nombre, apellido, tipoID, id_rol FROM persona "
               + "WHERE identificacion = "+ejemplo.getText().toString();
       String[] registros= new String[5];
       Conect cc = new Conect();
       Connection CC = cc.conexion();
        try {
            Statement sta= CC.createStatement();
            ResultSet res =sta.executeQuery(sql);
            if(res.next()){
                
                nombre.setText(res.getString("nombre"));
                apellidos.setText(res.getString("apellido").toString());
                id.setText(res.getString("tipoID").toString()+" "+res.getString("identificacion").toString());
                rol.setText(res.getString("id_rol").toString());
                
                System.out.println("Exito");
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Error "+ex);
        }
    }//GEN-LAST:event_ejemploBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton accesorio;
    private javax.swing.JButton aceptarObj;
    private javax.swing.JButton agregar;
    private javax.swing.JLabel apellidos;
    private javax.swing.JButton cancelarObj;
    private javax.swing.ButtonGroup checkVehiculo;
    private javax.swing.JPanel datos;
    private javax.swing.JTextField ejemplo;
    private javax.swing.JButton ejemploB;
    private javax.swing.JRadioButton elemento;
    private javax.swing.JRadioButton equipo;
    private javax.swing.JPanel foto;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nombre;
    private javax.swing.JFrame objeto;
    private javax.swing.JScrollPane objetoScroll;
    private javax.swing.ButtonGroup objetoTipo;
    private javax.swing.JPanel objetos;
    private javax.swing.JComboBox<String> opcion;
    private javax.swing.JPanel persona;
    private javax.swing.JLabel placa;
    private javax.swing.JLabel rol;
    private javax.swing.JLabel tipoV;
    private javax.swing.JRadioButton vNo;
    private javax.swing.JRadioButton vSi;
    private javax.swing.JPanel vehiculo;
    // End of variables declaration//GEN-END:variables
}
